on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Cache Python environment
      uses: actions/cache@v3
      id: cache-python
      with:
        path: .venv
        key: .venv-${{ hashFiles('requirements.txt') }}
    - name: Setup Apt for caching
      shell: bash
      run: |
        sudo apt-get update -yq
        sudo apt-get clean -yq
        aptHash(){ echo "$1-$(apt-cache policy "$1" | grep -oP '(?<=Candidate:\s)(.+)')"; }
        echo "aptVersion=$(aptHash texlive-base)-$(aptHash texlive-latex-extra)" >> $GITHUB_ENV
    - name: Cache deb files
      uses: actions/cache@v3
      with:
        path: .aptcache
        key: deb-${{ env.aptVersion }}
        restore-keys: |
          deb-
    - name: Restore deb files from cache
      shell: bash
      run: |
        if compgen -G ".aptcache/*.deb" > /dev/null; then
          sudo cp .aptcache/*.deb /var/cache/apt/archives/
        fi
    - name: Install base Apt packages
      id: cache-apt
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        execute_install_scripts: true
        packages: graphviz libgraphviz-dev librsvg2-bin pdf2svg
        version: 1.0
    - name: Install texlive Apt dependencies
      shell: bash
      run: |
        sudo apt-get install -yq texlive-base texlive-latex-extra
        mkdir -p .aptcache
        sudo cp /var/cache/apt/archives/*.deb .aptcache/
    - name: Build website
      shell: bash
      run: |
        tree src/_static/images
        make prod
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: 'dist'

  deploy:
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
