on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Cache Python environment
      uses: actions/cache@v3
      id: cache-python
      with:
        path: .venv
        key: .venv-${{ hashFiles('requirements.txt') }}
    - name: Install base Apt packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: graphviz libgraphviz-dev
        version: 1.0
    - name: Cache Images
      uses: actions/cache@v3
      id: cache-images
      with:
        path: src/_static/images
        key: ${{ hashFiles('src/images/*.tex') }}
    - name: Install texlive Apt packages
      if: ${{ !steps.cache-images.outputs.cache-hit }}
      run: |
        sudo apt-get install -yq librsvg2-bin texlive-full pdf2svg
    - name: Build website
      shell: bash
      run: make prod
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: 'dist'

  deploy:
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
